# Table of Contents {-}

 
 <font size="5"> Cross Tabulation Graphs </font>
 
 * <font size="4"> [Overall Graphs][Single Country Overall Graphs] </font> 
 * <font size="4"> [Overall Demographics Graphs][Single Country Demographic Plots] </font> 
 * <font size="4"> [Comparative Graphs][Comparative Overall Graphs] </font> 
 * <font size="4"> [Comparative Demographic Graphs][Comparative Demographic Graphs] </font> 
 
 
 
 <font size="5"> Trend Graphs </font>
 
 * <font size="4"> [Single Country Trend Graphs](#chapter-5) </font> 
 * <font size="4"> [Single Country Demographic Trend Graphs](#chapter-6) </font> 
 * <font size="4"> [Comparative Trend Graphs][Comparative Country Trend Graphs] </font> 
 * <font size="4"> [Comparative Demographic Trend Graphs][Comparative Country Demographic Trend Graphs] </font> 

 
 <font size="5"> **BARE BONES** Stacked Graphs </font>
 
 * <font size="4"> [Comparative Stacked Graphs][Stacked Plots] </font> 
 * <font size="4"> [Single Country Stacked Graphs][BARE BONES: Single Country Stacked Plots] </font> 
 
 
 <font size="5"> **BARE BONES** Multi-Question Graphs </font>
 
 * <font size="4"> [Single Country Multi-Question Plots][Single Country Multi-Question Plots] </font> 
 * <font size="4"> [Comparative Multi-Question Plots][Comparative Multi-Question Plots] </font> 
 * <font size="4"> [Single Country Multi-Question Trend Plots][BARE BONES: Single Country Multi-Question Trend Plots] </font> 
 
 
 <font size="5"> All Things Color </font>
 
 * <font size="4"> [Color Options][Color Options] </font> 
 * <font size="4"> [Change Default Colors][Change Default Colors] </font> 
 * <font size="4"> [Highlight Countries with Color][Highlight Certain Countries] </font> 
 
 
 <font size="5"> How Do I...? </font>
 
 * <font size="4"> [Change the Font Size][Change the Font Size] </font> 
 * <font size="4"> [Change the Title/Subtitle/Caption][Change the Title/Subtitle/Caption] </font>  
 * <font size="4"> [Only Show Certain Countries](#select-countries-chp) </font> 
 * <font size="4"> [Change the Order for Stacked Graphs](#order-change-stacked-graphs) </font>  
 
 
 <font size="5"> Appendix </font>
 
 * <font size="4"> [Guide Features][Guide Features] </font> 
 * <font size="4"> [Installing and Updating `ArabBarometR`][Installing and Updating `ArabBarometR`] </font> 
 
 
 