# COMING SOON: Single Country Demographic Trend Graphs

## Create Single Demographic Trend Graph

At the end, your code will look like the following:

```{r 06.1-Complete-Code-Example, eval=FALSE}

df_list <- list(
  survey1,
  survey2,
  survey3
)

survey_dates <- c("Survey 1",
                  "Suvey 2",
                  "Survey 3")


plot_trend_individual_demographics("Q1COVID19",
                                   "gender",
                                   df_list,
                                   survey_dates,
                                   "Algeria")


```


The code produces this graph:

```{r 06.2-Complete-Graph-Example, echo=FALSE, fig.dim=c(13,12)}

df_list <- list(
  survey1,
  survey2,
  survey3
)

survey_dates <- c("Survey 1",
                  "Suvey 2",
                  "Survey 3")


plot_trend_individual_demographics("Q1COVID19",
                                   "gender",
                                   df_list,
                                   survey_dates,
                                   "Algeria")


```
